### ISSUE TITLE
Add provenance information to new datasets

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#115]
For operations that return new dataset instances, the Cate operations framework should write metadata about the operation name, version, and arguments into the generated dataset (or just serialize its processing graph into dataset attribute).

We shall follow CF conventions, therefore always set the global `source` and `history` attributes as described in the [Description of File Contents](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#description-of-file-contents) chapter in the CF conventions.

Our `@op` decorator API could provide extra metadata fields for individual operations that generate new datasets.

**Comment by JanisGailis** [comment]
#143

**Comment by forman** [comment]
The `source` global attribute is not yet set from input values

**Comment by JanisGailis** [comment]
What do you mean? 'source' should already be set by people who generated the initial dataset.

**Comment by forman** [comment]
I understood, `source` is the data that were used to produce the new data dataset, not the sources for the datasets that are sources for the new one. Argh, let's close this issue.
