### ISSUE TITLE
Allow storing local data sources from CCI ODP subsets 

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#116]
We shall take full advantage of the ODP OPeNDAP feature for subsetting data sets, i.e. it shall be possible from the Cate API, CLI, and GUI to store a new local data source from an ODP spatiotemporal/variable subsets created from OPeNDAP data queries. 

This should become the default method to access ODP data, because it allows for using regional/variable subsets, but full time coverage of data. We believe this is one of the most common data access modes. Therefore we first should make sure it **can** be the default method by extensive performance testing.  

Furthermore 
* add option to update such local data source on remote changes (sync)
* add `cate.core.ds.add_local_data_source(name, file_pattern, update: bool)` API to allow for programmatical creation/updating of new/existing local data sources.

**Comment by kbernat** [comment]
Implemented. See #153
