### ISSUE TITLE
Local data store with temporal coverage information

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#121]
I would like to have this for daily->monthly aggregation to be able to save the resulting monthly files into local data store and then be able to use the resulting data source as a 'normal' monthly data source.

**Comment by JanisGailis** [comment]
#103

**Comment by JanisGailis** [comment]
@kbernat Any plans moving this forward? I need this to move on with UC06.

**Comment by JanisGailis** [comment]
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html

**Comment by forman** [comment]
When defining a local data store, temporal coverage should be extracted from netcdf files.

**Comment by kbernat** [comment]
Implemented. See also #153
