### ISSUE TITLE
Improve reusability of cate-core

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#125]
I propose a reorganization of packages in `cate-core` so that reusing them in other projects is made easier and the inclusion of incompatible transitive dependencies is mitigated. My aim is to restrict the dependencies of our sub packages on other Python libraries. Restriction may include having no dependencies at all or limit the number of dependencies.

Here is my proposal: 

### Cate specific packages

* `cate.core.*` - Dependencies: none or limit to xarray, geopandas (= our CDM). Move all useful, none-specific modules into new `cate.util.*`. Add `workspace` module from `cate.ui`.
* `cate.ds.*` - Dependencies: just xarray, geopandas (= our CDM). Won't touch this package.
* `cate.ops.*` - Dependencies:  xarray, numpy, scipy, ect. Won't touch this package, although it would be good to restrict use of matplotlib, basemap, cartopy to cate.ops.plot.* or so
* `cate.cli.*` - Dependencies: all cate-core dependencies. New package originating from `cate.ui.cli`.
* `cate.webapi.*` - Dependencies: all cate-core dependencies. New package originating from `cate.ui.*`.

As `cate.ui.*` will be fully distributed across other packages, it can be removed.

### None-Cate specific packages

* `cate.util.im.*` - Dependencies: just Tornado. New package originating from `cate.ui.imaging.*`.
* `cate.util.web.*` - Dependencies: just Tornado. New package originating from `cate.ui.*`.
* `cate.util.*` - Dependencies: none. New package originating from `cate.core.*` various modules.

Cate documentation for each package should then reflect this new setup and shall be kept up-to-date wrt the required dependencies..

We can have multiple package distributions which differ in their declared dependencies. Different Conda recipe folders can be used for this, e.g.

* `cate` - full distribution, includes all external dependencies
* `cate-light` - includes only core dependencies (or none at all?)

We have in fact a project that would profit from reusing some common cate functionality, e.g. Monitor, Config, WebSockets, etc. and therefore I have created a cate-core branch "cate-lib" where I started the refactoring.

**Comment by JanisGailis** [comment]
Just a heads up. In open_with_chunking I've refactored out get_lat_dim_name and get_lon_dim_name from the multiple places where they where used (cate.ops, cate.ui.workspace) and into util. You might want to pull those changes from that branch.

**Comment by forman** [comment]
@janis Isn't this something which is better off in `cate.core`, e.g. in `cate.core.cdm`? In `cate.utils`, I'd like to have more or less application independent code, not necessarily code that is used from multiple other modules.

**Comment by JanisGailis** [comment]
@forman Sure, wherever you feel it fits in best!
