### ISSUE TITLE
Image tile computation slow for chunked, compressed source data

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#128]
It currently takes up to 0.5 seconds (!) to compute a single 220 x 220 pixels image tile for a `analysed_sst` variable from e.g. 20000714120000-ESACCI-L4_GHRSST-SSTdepth-OSTIA-GLOB_LT-v02.0-fv01.0.nc, read with xarray. It has the following encoding:

    $ analysed_sst.encoding
    {'_FillValue': -32768,
     'add_offset': 273.14999,
     'chunksizes': (1, 663, 1327),
     'complevel': 1,
     'contiguous': False,
     'dtype': dtype('int16'),
     'fletcher32': False,
     'original_shape': (1, 3600, 7200),
     'scale_factor': 0.0099999998,
     'shuffle': True,
     'source': 'D:\\EOData\\SST\\20000714120000-ESACCI-L4_GHRSST-SSTdepth-OSTIA-GLOB_LT-v02.0-fv01.0.nc',
     'zlib': True}

Here is the performance analysis output generated while computing the tile:

    PERF: >>> Tile: res_1-analysed_sst-0-jet-0.0-1.0 0 0 0
    tile "arr-res_1-analysed_sst-0/0/0/0": computed, took 4.3165 sec
    tile "tra-res_1-analysed_sst-0/0/0/0": computed, took 4.3172 sec
    tile "tra-res_1-analysed_sst-0/0/0/0": stored in cache, took 0.0000 sec
    tile "rgb-res_1-analysed_sst-0-jet-0.0-1.0/0/0/0": computed, took 4.3218 sec
    tile "rgb-res_1-analysed_sst-0-jet-0.0-1.0/0/0/0": stored in cache, took 0.0010 sec
    PERF: <<< Tile: res_1-analysed_sst-0-jet-0.0-1.0 0 0 0 took 4.322905492520917 seconds

**Comment by JanisGailis** [comment]
I'm writing a test for automatic dask chunking upon opening a dataset, then I'll make a pull request for the branch, maybe this will also help in this issue, as theoretically you'd have to deal with better aligned chunking. Currently a single dask chunk that's being opened when constructing any tile woud be the whole time slice, irrespective of chunking on disk. With dask-chunked xarray dataset it would be less.

Notice also that constructing a 220x220 pixel large tile might involve ~500 redundant disk reads, in case each tile is handled separately.

The open_dash_chunk branch is now up to date with master, just lacks the test, so I guess you can try switching to it and see if it makes any difference!

**Comment by JanisGailis** [comment]
To elaborate what I said about 220x220 pixel tile.

When I tried using dask chunking initially I used very small chunks thinking that the smaller the chunk, the less memory I use. Then SHoyer explained that having many dask chunks in a single chunk on disk is not ideal, as that would mean that when working with each chunk dask would load in the whole chunk on disk resulting on many redundant reads, slowing the application down. So, the 'ideal' dask chunk is one that either holds an exact number of 'not-big' chunks on disk in it, or, close to that.

I don't know how you get the tile, but depending on the way it's done, it might involve reading the same chunk on disk (or with dask chunk size equal to time slice - the whole time slice, e.g. all chunks on disk) repeatedly.

So, trying larger tile sizes might actually be a good idea.

**Comment by forman** [comment]
@JanisGailis thanks for your comments! Please have a look at https://github.com/CCI-Tools/cate-core/blob/master/notebooks/xarray-and-chunks.ipynb and maybe try yourself.

> also that constructing a 220x220 pixel large tile might involve ~500 redundant disk reads, in case each tile is handled separately.

Yes, I'll try to get around this by creating an image pyramid's tile layout based on `chunksizes`. Currently, the tile size 220x220 is computed from lat/lon dimension sizes.

> I don't know how you get the tile, 

https://github.com/CCI-Tools/cate-core/blob/5974287f16bdbad792cf813717b32b0dce97d4ab/cate/util/im/image.py#L629-L658

**Comment by forman** [comment]
The current workaround gives a little better results:

    PERF: >>> Tile: res_1-analysed_sst-0-jet-0.0-1.0 0 0 0
    tile "arr-res_1-analysed_sst-0/0/0/0": computed, took 0.1870 sec
    tile "tra-res_1-analysed_sst-0/0/0/0": computed, took 0.1967 sec
    tile "tra-res_1-analysed_sst-0/0/0/0": stored in cache, took 0.0000 sec
    tile "rgb-res_1-analysed_sst-0-jet-0.0-1.0/0/0/0": computed, took 0.2017 sec
    tile "rgb-res_1-analysed_sst-0-jet-0.0-1.0/0/0/0": stored in cache, took 0.0012 sec
    PERF: <<< Tile: res_1-analysed_sst-0-jet-0.0-1.0 0 0 0 took 0.20303941936074565 seconds

**Comment by JanisGailis** [comment]
I looked into the notebook you made and added the same tests with using 'autochunking'. A few observations.

1. In your explorations you're not using dask at all. If you use xr.open_dataset without any chunking information given (even chunks={}), it defaults to using a NumPy array in the background. See the line where I call 'analysed_sst.data'.

So in this case chunks on disk are not used in any way.

2. With 'autochunking' there does not seem to be a difference in whether you do .load() beforehand or not, the time taken is ~120ms in both cases.

**Comment by forman** [comment]
> In your explorations you're not using dask at all.

Then it is very strange that the `tile.load()` call is now consuming 99% of the tile load time. Before I added the call, the 99% of the time was spend when data was actually pulled from xarray by mapping raw data to RGBA arrays and then to PNG image tiles.

> So in this case chunks on disk are not used in any way.

I believe, that is not entirely true because chunking is part of the encoding of the data on disk and therefore it is something the underlying decoding engine must deal with (which is `netCDF4` by default).

**Comment by forman** [comment]
Current performance is now accepatable
