### ISSUE TITLE
Spatial, temporal and variable selection objects

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#130]
Data types with special meaning, e.g. GeoPoint, GeoBox, TimeRange, etc. for which we then create fancy input GUI components. For example, if some operation has a parameter "region" of type GeoBox, users can pick an existing region from "My Places".

See also #46 and #72 

- [x] Spatial object Point
- [x] Spatial object Polygon
- [x] Temporal selection object 
- [x] Variable selection object

**Comment by JanisGailis** [comment]
Shapely seems like a good candidate for spatial objects:
http://toblerity.org/shapely/manual.html

We could use ```shapely.Point``` for lat/lon points and either ```shapely.LinearRing```, ```shapely.Polygon``` or ```shapely.MultiPolygon``` for other geometric objects.

A ```LinearRing``` is a closed collection of lines that don't cross themselves.
A ```Polygon``` is a single polygon that can have holes
A ```MultiPolygon``` is a collection of non-overlapping ```Polygon``` features

For interoperability with the GUI, the possibility to convert Shapely objects to Well Known Text [[1]](https://en.wikipedia.org/wiki/Well-known_text) [[2]](http://toblerity.org/shapely/manual.html#well-known-formats) might come in handy.

If we at some point use Shapely to handle a large amount of features, ```Shapely.speedups``` [[3]](http://toblerity.org/shapely/manual.html#performance) might come in handy.

**Comment by forman** [comment]
Janis, I agree, let's go for shapely! I believe, it is a geopandas dependency anyway.

**Comment by JanisGailis** [comment]
- [ ] Spatial object Point
- [ ] Spatial object Polygon
- [ ] Temporal selection object

**Comment by JanisGailis** [comment]
Issue #46 has now been closed, so we have a new flexible way to define complex types for use in operations and to facilitate the integration with the GUI. This can/should now be used to create complex types to use across the board wherever spatial/time/variable selection is required.

**Comment by JanisGailis** [comment]
PR #152
