### ISSUE TITLE
Automate installer builders

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#131]
We must urgently automate building of installers for Cate:

- [x] Develop concept how to bundle Conda env with Electron app (or the other way round!)
- [x] Develop concept how safely install Conda env from Electron app (or the other way round!) when it is first run
- [x] Linux and MacOS: Configure Travis to build Cate conda installers and publish them
- [x] Windows: Configure AppVeyor to build Cate conda installer and publish it 
- [x] Linux and MacOS: Configure Travis to build Cate Desktop electron installers and publish them 
- [x] Windows: Configure AppVeyor to build Cate Desktop electron installer and publish it

**Comment by cpaulik** [comment]
Just saw the ? at the at the mac build. https://circleci.com/pricing/#faq-section-os-x should offer free Mac builds for open source projects.

**Comment by forman** [comment]
@cpaulik Thanks for the hint! We just managed to create Conda installers for Mac using Travis. Now we will configure Electron installer builds for [Cate Desktop](https://github.com/CCI-Tools/cate-desktop).

**Comment by mzuehlke** [comment]
Based on discussion https://github.com/CCI-Tools/cate-core/wiki/Software-Installation-Approach#bundling-the-frontend-and-the-backend-installer we decided to not bundle the two installers.
