### ISSUE TITLE
Create a new Tag for Support Requests

### ISSUE THREAD

**Issue by acorlyon** [CCI-Tools/cate-core#136]
We need to keep track of any issues/ problems/ questions that are from users and report back to ESA at the end of each iteration.    Instead of using a ticketing system we are using this Issue Tracker so we need a Tag for "Support Requests" so we can easily find these issues.

**Comment by forman** [comment]
We now have the following labels for user support:

* "support request" (new, should be used for requests from outside users)
* "help wanted" (existed before, can also be used by team mates)
* "question"

Not that labels cannot be assigned by users.
