### ISSUE TITLE
Revision of Cate's Data Management

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#153]
We need a slight revision of Cate's Data Management, especially a revised `cate.core.ds.DataSource` interface. Details are here:
https://github.com/CCI-Tools/cate-core/wiki/Revision-of-Cate's-Data-Management

- [x] Introduce new `DataSource.open_dataset` API, add more constraint args, deprecate `protocol` arg, use new types, generalise towards any return type (forman) 
- [x] Introduce new `DataSource.make_local` API (forman) 
- [x] Rename LocalFilePatternDataStore and LocalFilePatternDataSource to LocalDataStore and LocalDataSource (forman)
- [x] Reimplement all `open_dataset` overrides wrt deprecate `protocol` arg and support new constraint params (kbernat)
- [x] Implement `make_local` overrides, reuse old `sync`method and Chris' new code (kbernat)
- [x] Use new `open_dataset`  constraint args in CLI + GUI (forman)
- [x] Use new `make_local`  in favor of `sync` where appropriate. We might keep private `_sync` method as an implementation detail (forman, kbernat)
- [x] Increase `cate.core.ds` and `cate.ds` code coverage by unit-tests (kbernat)

**Comment by JanisGailis** [comment]
Looks good.

One note. When using a 'PolygonLike' from new types, one has to keep in mind that what one can get might be whatever valid polygon. Then, it depends on what OpenDAP can do, but probably a bounding box has to be extracted and used for selection.

One question though is what to do with values that are in the bounding box, but not part of the polygon. In the 'subset_spatial' operation I plan to mask these with NaN. I'm not sure what would be the best approach upon opening - mask with NaN, create a 'mask' variable, or just select the bounding box.

**Comment by forman** [comment]
> ..., but probably a bounding box has to be extracted and used for selection.
Yepp!

> In the 'subset_spatial' operation I plan to mask these with NaN.
Please make this an optional behavior. e.g. use new kwarg `mask_polygon_exterior: bool = False`.

**Comment by kbernat** [comment]
Hi Norman,
in make_local method, do we need both local_name and local_id? Role of local name is obvious but how should we use second parameter, is it kind of suffix for general (ecv) name?

> 1. Replace sync by make_local
> 
> For this, the DataSource method sync shall be replaced by make_local and shall receive a new parameter **local_id**. ...

```
def make_local(self,
               local_name: str,
               local_id: str = None,
               time_range: TimeRangeLike.TYPE = None,
               ...
```
