### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#154]
Latest builds update Matplotlib to 2, this is what potentially breaks the build:

https://github.com/matplotlib/matplotlib/issues/8180
https://github.com/conda-forge/libxslt-feedstock/issues/8
https://github.com/conda-forge/staged-recipes/issues/673#issuecomment-279317324

**Comment by mzuehlke** [comment]
Fixed  by adapting the syntax in the environment files. Version syntax "package =>a,<b" does not exclude brc1 so the format "package a*" is better suited.
See the following commits:
90dbfc902eea4ce09cf9807228d7c1e1c5625ae2
6caaea653e2db4fcc480c2907cd5df83fa96c65c
ff6df01b0a4ed732e7f776f2914897bef678a66d

Total diff:

**Comment by mzuehlke** [comment]
Fixed  by adapting the syntax in the environment files. Version syntax "package =>a,<b" does not exclude brc1 so the format "package a*" is better suited.
See the following commits:
90dbfc902eea4ce09cf9807228d7c1e1c5625ae2
6caaea653e2db4fcc480c2907cd5df83fa96c65c
ff6df01b0a4ed732e7f776f2914897bef678a66d

Total diff:
https://github.com/CCI-Tools/cate-core/compare/38e51a9d7bcf20d214e9dc0cc19b63bb599b95ba...ff6df01b0a4ed732e7f776f2914897bef678a66d
