### ISSUE TITLE
Use generic types in user interfaces and docs

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#158]
The new generic types introduced by #130 must be used in the various user interfaces

- [ ] API used in IPython Notebooks (fix code)
- [x] CLI, e.g. display `cate op list <op>` and argument parsing, `cate res set <op> <arg1>=<val1> ...`
- [x] GUI, e.g. display of op help in OPERATIONS panel, parameter entry editors, ...

I have no clue how we tell **Sphinx** to use simple type names instead of using totally confusing expressions composed of `typings.Union`.

**Comment by JanisGailis** [comment]
API notebooks can be fixed only after #172 is closed. This is, of course, on me.
