### ISSUE TITLE
Let CLI display temporal coverage of datasets

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#16]
When listing available data sources e.g.

```
ect ds list
```

it would be very helpful for users if also the temporal coverage of the available data sources is displayed.

See also #14.

**Comment by kbernat** [comment]
@forman 
Looks like it's already implemented. Is there anything to be added or changed in this feature?

**Comment by forman** [comment]
@kbernat not sure what you mean. if I `cate ds list`, I get:

       1: esacci.AEROSOL.5-days.L3C.AEX.GOMOS.Envisat.aergom.2-19.r1
       2: esacci.AEROSOL.climatology.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1
       3: esacci.AEROSOL.day.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1
    ...
     233: esacci.SST.satellite-orbit-frequency.L3U.SSTskin.ATSR.ERS-1.ATSR1.1-1.1996
     234: esacci.SST.satellite-orbit-frequency.L3U.SSTskin.ATSR.ERS-1.ATSR1.1-1.1997
     235: local.CLOUD_07
     236: local.OZONE_07

No temporal coverage.

**Comment by kbernat** [comment]
@forman You are right! Looks like I focused on `ds info` instead of `ds list`

**Comment by forman** [comment]
I think it is a nice-to-have.
