### ISSUE TITLE
Use new type `VariableNamesLike` in operations and link with source

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#166]
Operations following a similar signature like

     def some_op(ds: xr.Dataset, var: str, ...):
          ...

should now do the following
     
     @op_input('ds')
     @op_input('var', value_set_source='ds', data_type=VariableNamesLike)
     def some_op(ds: xr.Dataset, var: VariableNamesLike.TYPE, ...):
          ...

so I can create variable selectors in the GUI.

**Comment by JanisGailis** [comment]
There is a small issue with this.

There are a few operations where I explicitly need a single variable name, while VariableNamesLike resolves to a list of ```fnmatch``` patterns.

Should we have a separate VariableNameLike -> str type, or should I just use the existing one and check if I got what I wanted to have?

**Comment by forman** [comment]
Hi Janis, is it actually a `Like`? Why not just `VariableName` whose `TYPE` is just a `Optional[str]`. In addition, there is also a property `nullable` which you can use to tell that a parameter of type `VariableName` must not be given.

**Comment by forman** [comment]
I vote for `VarNamesLike` and `VarName`, or `VarNameLike` if you prefer. Those are shorter and look better in the UI.

**Comment by JanisGailis** [comment]
OK.

Can ```VarName```  be a simple alias of ```str``` or do you prefer a class?
