### ISSUE TITLE
Missing global attributes in multi-file netCDF Datasets

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#174]
The `attrs` field of datasets we get from `cate.core.ds.open_dataset` always seems to be empty.

**Comment by mzuehlke** [comment]
Seems to be an xarray problem: 
Issue pydata/xarray#1037
PR pydata/xarray#1038

**Comment by mzuehlke** [comment]
Fixed by using a newer xarray version.
See #194
