### ISSUE TITLE
"cate ds make_local" CLI issues

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#188]
- [x] name is not obvious, better use `copy`
- [x] make `NEW_DS` optional, default should be  "local.<REF_DS>", so `copy` can be a replacement for `sync`
- [x] maybe use options for the three constraints time, region, variable names
- [x] don't fail if local data source exists, instead heal or complete an incomplete data source, see discussion  in #193
- [x] remove `cate ds sync` command (which currently fails with `cate ds: error: ('Unsupported protocol', None)`)
- [ ] update all documentation to reflect the changes

**Comment by forman** [comment]
Blocker, because currently `cate ds sync TIME` doesn't seem to work anymore

**Comment by kbernat** [comment]
Implementation is done. documentation update in progress.
