### ISSUE TITLE
CLI progress monitor broken

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#189]
The progress monitor displayed by the CLI is broken. Instead of staying in one line, it prints a new line on every update, which is extremely annoying.

![image](https://cloud.githubusercontent.com/assets/206773/25136635/df04f41a-2455-11e7-9ede-f0e803b3eb9f.png)

**Comment by mzuehlke** [comment]
This seems to be a window problem. On Linux the progress monitor stays on the same line.

**Comment by kbernat** [comment]
Thanks for testing, I was the last who touched it.. and worked/tested it on Linux :)

**Comment by kbernat** [comment]
Fix tested on Windows and worked fine.
