### ISSUE TITLE
Python API docs shall include linked type annotations

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#19]
Although we Sphinx' `sphinx_autodoc_annotation`  option, the generated type information is not linked with the type's API docs. For example, if a type is `xarray.Dataset` the type annotation shall be linked like so: [xarray.Dataset](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html).

This is very important as we use xarray.Dataset as our common data model.

**Comment by mzuehlke** [comment]
We need to use `sphinx.ext.intersphinx` to add links. 
See:
http://www.sphinx-doc.org/en/stable/ext/intersphinx.html

**Comment by forman** [comment]
Works now, but the current solution is still a bit ugly. Especially types from Python `typing` libary are not well represented and make function signatures nearly unreadable.
