### ISSUE TITLE
Error when loading specific ODP-Dataset

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#211]
The following was reported by our intern while testing UC06 and trying to open a different dataset to test with.

_The following CLI:_
cate res open n18  
esacci.CLOUD.day.L3U.CLD_PRODUCTS.AVHRR.NOAA-18.AVHRR_NOAA.1-0.r1  
2007-01-01 2007-12-31

_Returns:_
Errorcode: cate res: error: unable to decode time units 'Julian Date, days elapsed since 12:00 January 1, 4713 BC' with the default calendar.

**Comment by forman** [comment]
Can this be reproduced on master? It seems to originate from the `time` coordinate variable in the NetCDF files contributing to `esacci.CLOUD.day.L3U.CLD_PRODUCTS.AVHRR.NOAA-18.AVHRR_NOAA.1-0.r1`in the range 2007-01-01 to 2007-12-31.

**Comment by HerzogStephan** [comment]
I try asap.

**Comment by JanisGailis** [comment]
The product in question was one of the old cloud CCI datasets, that doesn't exist on the portal anymore. The new ones should have proper CF compliant time axis.

If a similar problem persists, please report a new Issue!
