### ISSUE TITLE
Vague Error-Message when typo in var

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#212]
The following was reported by our intern while testing UC06.

_Following CLI:_
cate res set noaa17cl_cctot select_var ds=noaa17cl var=cc_tota

_Errorcode:_ 
cate res: error: input 'ds' for operation 'cate.ops.select.select_var' must be of type 'Dataset', but got type 'str'

Depending on the backround of a user, the user might not know where to look at.

**Comment by JanisGailis** [comment]
Is this after you have pulled the latest version?

I think the syntax of denoting results of other operations has changed now to ```ds=@noaa17cl```. I don't this is documented anywhere.

As for the error message.. I'm not sure it can be made much clearer :)

**Comment by forman** [comment]
Use the new at-character! It must read ds=@noaa17cl

**Comment by forman** [comment]
(cate) C:\Users\Norman\IdeaProjects\ccitools\cate-core>cate res set -h
usage: cate res set [-h] [-d DIR] NAME OP ...

positional arguments:
   NAME               Name of a new or existing target resource.
   OP                 Operation name. Type "cate op list" to list available
                      operation names.
   ...                Operation arguments given as KEY=VALUE. KEY is any
                      supported input by OP. VALUE depends on the 
expected data
                      type of an OP input. It can be either a value or a
                      reference an existing resource prefixed by the add
                      character "@". The latter connects to operation steps
                      with each other. To provide a (constant)value you 
can use
                      boolean literals True and False, strings, or numeric
                      values. Type "cate op info OP" to print 
information about
                      the supported OP input names to be used as KEY and 
their
                      data types to be used as VALUE.

optional arguments:
   -h, --help         show this help message and exit
   -d DIR, --dir DIR  The workspace's base directory. If not given, the 
current
                      working directory is used.

**Comment by HerzogStephan** [comment]
Our intern did not worked with the Version, where at-syntax was included.

**Comment by forman** [comment]
Stephan, can we close this?
