### ISSUE TITLE
Testdata for UC02

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#229]
As input-data for UC2 I want to provide a text-file, that contains times and values to some variable. What kind of format/structure must the data have to be able to be read by 'cate res read -f TEXT'?

Can we also enable the toolbox to read .csv-files?

**Comment by JanisGailis** [comment]
The toolbox can read .csv files, I believe it returns a pandas dataframe to work with. Haven't tested this though.

**Comment by HerzogStephan** [comment]
The tbx does not report on any structure or format it requires. I will test it further.

**Comment by JanisGailis** [comment]
Can we close this?

By the way, if you have a .csv file you want to use for UC2, I'd be happy to have it!

**Comment by HerzogStephan** [comment]
I started to write a py-script creating pseudo-data, but I will shift to real data and make it available asap.
