### ISSUE TITLE
Harmonize data schema of ingested datasets ("CDM")

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#23]
When ECT opens a dataset, e.g. from the CCI ODP, it shall make sure that the resulting (`xarray.Dataset`) in-memory representation conforms to a unique schema that we'd can expect in all our data operations. This is also what we refer to as _Common Data Model_ (CDM).

Harmonization shall address:
- Different names used for _latitude_ and _longitude_ for both dimensions and coordinate variables
- Different interpretation to which actual _location_ a given lat/lon coordinate value refers to within a grid's cell boundaries
- Different names used for _time_ and _time boundaries_, as well as time data types.
- Variable interpretation, e.g. distinguish between _primary_, _auxiliary_ (e.g. uncertainty), or _coordinate variables_ (e.g. latitude) 
- Minimum set of metadata (global) attributes, e.g. the _data source name_ from which the dataset has been opened, the processing history in form an ECT _Workflow JSON_ dump.
- Not-a-value management: `missing_value`, `_FillValue`, `NaN`

**Comment by forman** [comment]
Can we close this?

**Comment by JanisGailis** [comment]
I think we can close this. ```ops.open_dataset``` is ```normalize=True``` by default.

**Comment by forman** [comment]
Ok.
