### ISSUE TITLE
Use ODP CSW service as primary metadata source

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#240]
### Expected behavior

Our remote ODP data stor implementation should be changed so that its primary metadata source is the ODP's CSW service, which will provide to Cate the following additional dataset meta-information:

* Temporal and spatial coverage of each dataset
* Dimension names and shape (= dimension sizes) of each dataset / variable
* A dataset's human-readable citation information, Terms of Use information, as well as a title.
* Overall dataset sizes in bytes

This can be done by using the CSW interface in conjunction with the ESGF search API as is implemented by the CCI Open Data Portal Search user interface.  The steps are:

1. CSW query using search facets (same facet names as used by ESGF
2. For each ISO record result extract the identifier(s) for the equivalent ESGF datasets
3. Query ESGF search API using the ESGF dataset identifiers extracted in 2.

### Actual behavior

We don't use the CSW so far and are thus lacking the important meta-information listed above.

### Steps to reproduce the problem

Type `cate ds info DS` or watch the GUI's details panel on a selected remote dataset.

* Temporal coverage is derived or OPeNDAP or from filenames which takes too long to compute.
* Can't make reasonable assumptions of the dataset sizes to be downloaded and how long it will take
* We have no human-readable dataset names or descriptions

### Specifications 

Cate 0.8.0rc2

**Comment by kbernat** [comment]
- [X] Temporal and spatial coverage of each dataset
- [ ] Dimension names and shape (= dimension sizes) of each dataset / variable
- [X] A dataset's human-readable citation information, Terms of Use information, as well as a title.
- [X] Overall dataset sizes in bytes

At the moment there is no information about dimsension names or shape in catalogue
