### ISSUE TITLE
Issues with coregister operation

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#241]
### Expected behavior

[Use case 9](http://ect-core.readthedocs.io/en/latest/use_cases.html#relationships-between-aerosol-and-cloud-ecv) should still work with current Cate state. I used CCI Ozone and Cloud datasets.

### Actual behavior

If I do the co-registration before subsetting, then `coregister` reports:

    cate res: error: Failed at nopython (nopython frontend)
    Failed at nopython (nopython frontend)
    Cannot resolve setitem: array(float32, 1d, C)[int64] = array(float32, 1d, C)
    File "..\..\cate\ops\resampling.py", line 425
    [1] During: typing of setitem at c:\users\norman\ideaprojects\ccitools\cate-core\cate\ops\resampling.py (425)
    [2] During: resolving callee type: type(CPUDispatcher(<function _downsample_2d at 0x0000029E088746A8>))
    [3] During: typing of call at c:\users\norman\ideaprojects\ccitools\cate-core\cate\ops\resampling.py (236)

or if I do the subsetting first, I get from `coregister`:

     cate res: error: The provided dataset does not seem to be global, equidistant and pixel-registered.

See also #224.

### Steps to reproduce the problem

Follow steps in [uc09.bat](https://github.com/CCI-Tools/cate-core/blob/master/scripts/uc09.bat).

### Specifications 

Cate 0.8.0rc2

**Comment by JanisGailis** [comment]
Global datasets seem to work (not produce an error), yet the result seems spectacularly off:
![coregistration](https://user-images.githubusercontent.com/9655353/26984349-5f8f5af0-4d3f-11e7-8190-4abee678f6e6.png)

**Comment by JanisGailis** [comment]
The above garbled output was due to masking NaN values. Now the array slices on which coregistration is performed are converted to numpy masked arrays, then NaN values are ignored in computation and preserved in the output.
