### ISSUE TITLE
pandas.tslib warning

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#244]
(Just to make sure that we are aware of it!)
### Expected behavior
No warning.

### Actual behavior

Cate gives a warning message:
[...]/python3.5/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.

### Steps to reproduce the problem

1. *type: cate -h*

### Specifications 

*Cate Version 0.8.0rc3 for linux.*

**Comment by forman** [comment]
This caused by the current `xarray` version 0.9.5. It has been already fixed in 0.9.6, but it is not yet released.

**Comment by mzuehlke** [comment]
xarray 0.9.6 has been release.
