### ISSUE TITLE
pearson_correlation too slow

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#273]
### Expected behavior

The `pearson_correlation` operation should execute fast as it uses simple, linear maths.

### Actual behavior

It is way too slow. Computing of average size lat/lon images of a few megapixels can easily take minutes.

### Steps to reproduce the problem

Run use case 9.

### Specifications 

0.8.0rc7.dev2

**Comment by forman** [comment]
Once we've successfully optimized the operation, e.g. using [Numba](http://numba.pydata.org/), we should document this in a dedicated section of the developer guide.

**Comment by JanisGailis** [comment]
See also #201

**Comment by forman** [comment]
Oops, I should have added a comment rather than createing a new issue.

**Comment by JanisGailis** [comment]
It's fine, more issues to close :) I think I would add it to 'Operation development guidelines' as 'Optimization' or something.

**Comment by JanisGailis** [comment]
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   124        81          130      1.6      0.0      for lai in range(0, len(lat)):
   125      6480        20297      3.1      0.0          for loi in range(0, len(lon)):
   126      6400     38844444   6069.4     17.1              x = array_x.isel(lat=lai, lon=loi).values
   127      6400    186450590  29132.9     82.1              y = array_y.isel(lat=lai, lon=loi).values
   128      6400      1621394    253.3      0.7              corr_coef[lai, loi], p_value[lai, loi] = pearsonr(x, y)
```
It's slow not due to the calculation, but rather because of data access across the dask array distributed between files.

forcing explicit reading of the whole selected array into memory:
```python
array_y.load()
array_x.load()
```

proves the point:
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   127        81          107      1.3      0.0      for lai in range(0, len(lat)):
   128      6480        14817      2.3      0.1          for loi in range(0, len(lon)):
   129      6400      4614680    721.0     44.9              x = array_x.isel(lat=lai, lon=loi).values
   130      6400      4453011    695.8     43.4              y = array_y.isel(lat=lai, lon=loi).values
   131      6400      1119590    174.9     10.9              corr_coef[lai, loi], p_value[lai, loi] = pearsonr(x, y)
```

Naively using Numba won't solve the performance issue, rather, it should be explored if the calculation can be vectorized across the array to minimize i/o and leverage parallel processing capabilities of Dask.

**Comment by JanisGailis** [comment]
Managed to reduce running time of Pearson correlation by a few orders of magnitude:
```
Total time: 0.773345 s
```

**Comment by forman** [comment]
!

**Comment by forman** [comment]
Can we close this now? I mean, is it as fast as can be ;)

**Comment by JanisGailis** [comment]
I think we should close issues only when relevant code ends up on master. So, once I'm finished with the improvements to correlation, I'll make a PR and denote which Issues would be closed by that PR!
