### ISSUE TITLE
Limit possible operation tags

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#280]
### Expected behavior

Operations should only use tags from a limited and agreed-on set.

- [x] aggregate
- [x] anomaly
- [x] arithmetics
- [x] coregistration
- [x] correlation
- [x] index
- [x] io
- [x] outliers
- [x] pandas
- [x] plot
- [x] resampling
- [x] select
- [x] subset
- [x] timeseries
- [x] utility

### Actual behavior

We have 20+ op tags. See dropdown list in GUI.

### Specifications 

0.9.0.dev3

**Comment by JanisGailis** [comment]
Can you provide the initial input to such a set? As in, which tags it makes sense to have from user's perspective when using the GUI?

**Comment by forman** [comment]
When I was young, I wrote https://github.com/CCI-Tools/cate-core/wiki/Operation-Tags

**Comment by JanisGailis** [comment]
That's a good initial set. I'll use those tags and raise the question if there is an operation that doesn't fit well within that set. So, according to that list 'pearson_correlation_*' would only have the ```utility``` tag.

**Comment by forman** [comment]
Plus the `correlation` tag, because it is its module name.

**Comment by forman** [comment]
Ah, but we could add that automatically - right?

**Comment by JanisGailis** [comment]
It could be done automatically, and if it's done it should be done automatically. I'm just wondering if we actually want to put module names as tags. I mean, it makes sense to have them. But then, there are currently 16 operation modules in cate/ops. Add 7 tags mentioned in the wiki and we're back to 20+.

**Comment by forman** [comment]
You're right. So let's *not* auto-tag.

**Comment by JanisGailis** [comment]
I'm going over all operations to check if the tags used are not too extensive. E.g. each operation might have a module tag (not necessarily), and maybe a tag from the list in the wiki.

**Comment by forman** [comment]
@JanisGailis any news here?

**Comment by JanisGailis** [comment]
@forman Moving it to paused must have been done by mistake. As far as I'm concerned, this is done. I've gone over all operations and limited the tags to what we have in wiki + (maybe) module name.

**Comment by forman** [comment]
Looks ok now:

![image](https://user-images.githubusercontent.com/206773/30736251-4c52b23a-9f82-11e7-8542-d130bae1aea3.png)
