### ISSUE TITLE
Merge meta_data and meta_info

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#301]
### Expected behavior

There should be a single property in a (local?) data source's JSON representation that provides the data source's meta information, e.g. `meta_info` as defined in the `DataSource` interface.

### Actual behavior

We currently find the JSON properties `meta_data` and `meta_info`. Why keep two?

See [code](https://github.com/CCI-Tools/cate-core/blob/d6b0669b931dcb03ed7a6871c84652dd8e1e1bfd/cate/ds/local.py#L516-L533)

### Specifications 

Cate 0.9.0.dev4

**Comment by kbernat** [comment]
Still possible to read obsolete format, new datasets use only new/common meta_info structure.
