### ISSUE TITLE
Cannot select time constraint from calendar

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#303]
### Expected behavior

In the “Download remote data source” window, expect to be able to select a time constraint by clicking on a date in the calendar

### Actual behavior

Two issues:
•	The calendar is superimposed over the rest of the window, making it difficult to see 
•	Some of the dates cannot be clicked and selected

### Steps to reproduce the problem

1.	From ESA CCI Open Data Portal list, select esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1 then click on “Download and/or open remote dataset”

2.	In the “Download Data Source” window:
•	Select time constraints.  
•	In the start time box, type 2002-01-01
•	Now try to change the date using the calendar (Jan 2002) below. Click on “16” in the calendar
•	Observe that start date does not change.

![hc044](https://user-images.githubusercontent.com/29569434/28822265-8272d78c-76b0-11e7-881d-7b091faeb1f1.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
I can reproduce this.

It happens only with the date selector in the download dialog, not with in the same components in e.g. subset_temporal.

**Comment by HelenClifton** [comment]
Confirmed fixed in cate-0.9.0.dev.6
