### ISSUE TITLE
"Switch to resource selection" option when editing operation step

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#310]
### Expected behavior

Select an operation. "New Operation Step" window opens. Expect to be able to select different parameters.

### Actual behavior

Parameters which are **NOT** of type Dataset have a toggle switch next to them which gives the option to "Switch to resource selection" . When this is selected, a drop-down list is shown but it is not possible to select any resource. In any case, it does not make sense to select a resource for certain parameters such as string types.
Same behaviour is seen in "Edit Operation Step" window.

### Steps to reproduce the problem

_The example is given for coregister operation, but the same is seen with other operation types._

1. Open cate GUI and ensure that at least two resources have been created in the workspace. 
2. In Operations panel, double-click on an operation, e.g. coregister.
3. In the New Operation Step window, verify that a resource can be successfully selected for a parameter of type Dataset (ds_master and ds_slave)
4. In the New Operation Step window, select the "switch to resource" next to parameter method_us (type string)
5. In the New Operation Step window, select the "switch to resource" next to method_ds (type string)

![hc 051 1](https://user-images.githubusercontent.com/29569434/28835523-7e5a5346-76dd-11e7-8c5e-fbd544d23006.PNG)

6. Observe a "select resource" drop-down list is seen but it is not possible to select any resource.

![hc 051 2](https://user-images.githubusercontent.com/29569434/28835601-da0b34c6-76dd-11e7-95e4-3842878f426e.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
A resource _may_ provide a string, too. But you are right the current behavior is not straight forward.
Now the switch is only enabled when the drop-down box would contain any **compatible resource**.
