### ISSUE TITLE
Data Source title not used or displayed on GUI

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#311]
### Expected behavior

When creating a new local data source from a remote one, there is a field in the "Download Data Source" window named "Data source title (optional)". After the new local data source is created, would expect this title (if it is filled in) to be shown somewhere on the GUI (perhaps in Meta-Info?)

### Actual behavior

The contents of "Data source title (optional)" do not seem to be used in any way. The data source title is not displayed anywhere on the GUI . It is confusing for user.

### Steps to reproduce the problem

1.  Select a remote data source from the list and click "Download and/or open remote dataset"
2. In "Download Data source" window, select "Download and make local data source" 
3. Fill in a data source title 

![hc042](https://user-images.githubusercontent.com/29569434/28870312-b650fc10-7777-11e7-909b-4f16f0a7d50b.PNG)

4. Click "Download"
5. Once the local data source has been created, open it. Try to find the data source title as entered by the user.

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
The GUI currently does not propagate that information to the backend.
But the backend missed the improvements to `make_local` to handle this information.
See #287

**Comment by forman** [comment]
We're about to change the way how to make data sources local. The data source title will not yet be part of it, see #366, as users can provide it through their own `local_ds_id`. Later, the GUI would allow users to change the display title of a local data source at any time.

**Comment by forman** [comment]
Closing this. May reopen when we have the title field back when creating local data sources.
