### ISSUE TITLE
Lat and lon displayed at bottom of GUI when cursor is off globe

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#312]
### Expected behavior

When World view is opened and cursor is on globe, lat/lon is displayed in blue bar at the bottom of the GUI.
However when cursor is on one of the panels, no lat/lon should be displayed.

### Actual behavior

When cursor is located on a part of the globe which is behind a panel, the actual lat/lon is displayed:

![hc0571](https://user-images.githubusercontent.com/29569434/28875511-b2aff5b4-778d-11e7-9d5a-18631f42f78b.png)

When cursor is located off globe, a random lat/lon is displayed:

![hc0572](https://user-images.githubusercontent.com/29569434/28875582-e945df26-778d-11e7-846f-3661c9e848aa.png)

### Steps to reproduce the problem

1. Open GUI 
2. Ensure World view is open
3. Click on one of the panels
4. Move cursor around GUI and look at lat/lon which is displayed at bottom of GUI

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
In the long run, move coordinates from status bar to screen overlay.
