### ISSUE TITLE
List of variables and their values / units seems to be incorrect

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#316]
### Expected behavior

In Data Sources panel, expect list of variables with name and units to be displayed.

### Actual behavior

It is not clear what the Units column should contain. 
- sometimes it contains values only. 
- sometimes it contains both values and units
- sometimes it contains units only

In many cases, the units column contains "1" which doesn't seem like a sensible value.

This is a general problem across different datasets.

### Steps to reproduce the problem

1. From list of remote data sources, select esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1 
2. Select Details then click on Variables
3. Look at contents of Units column

![hc 046 1](https://user-images.githubusercontent.com/29569434/28964124-6f8aa604-7903-11e7-9059-f34c0bc2e7e7.PNG)

4. From list of remote data sources, select esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1
5. Look at contents of Units column

![hc 046 2](https://user-images.githubusercontent.com/29569434/28964218-c23b4c82-7903-11e7-972c-6305b07bfd79.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by HelenClifton** [comment]
see also #319

**Comment by mzuehlke** [comment]
We can only display the units that are provided by the ODP servers.
A "1" is common nomenclature for specifying that a variable is "unitless".

> The conforming unit for quantities that represent fractions, or parts of a whole, is "1".
See: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#units
