### ISSUE TITLE
Inconsistency between variables displayed on Data Sources panel and on Variables panel

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#319]
### Expected behavior

Dataset variables are displayed both on the Data Sources panel (under Variables link) and on the Variables panel. Expect these lists to contain the same variables. Also that if a variable is selected on the Data Sources panel the same variable becomes selected on the Variables panel.

### Actual behavior

Some variables seen in list on Data Sources panel are not in list on Variables panel.
Selecting a different variable on Data Sources panel  does not change variable selected on the Variables panel. This is confusing because the user is then seeing the details of a different variable in the Variables panel.

### Steps to reproduce the problem

1. Highlight data source: esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1
Click on “Download and/or open remote dataset”
In “Download Data Source” window:
•	Select Time Constraint and select start time of 2007-01-01 and end time of 2007-03-31
•	Leave the Region constraint and the Variable constraint unselected.
•	Select “Download and make local data source” and leave the default unique ID
•	Leave “Open dataset from local data source” unselected
•	Click on “Download”

![hc 063 1](https://user-images.githubusercontent.com/29569434/28970597-103391a2-7921-11e7-81b7-7099c1982a2f.PNG)

2. Highlight data source: local.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1. Select Details then click on Variables

![hc 063 2](https://user-images.githubusercontent.com/29569434/28970608-16e09bee-7921-11e7-8c97-4769291da605.PNG)

3. Click on “Open local dataset” 
Do not select Time Constraints, region constraints or variable constraints. 
Click “Open Local”

4. In Workspace panel, click on the resource which has been created for the dataset. Open Variables panel. Some variables (**air_pressure**, **layers**) which are displayed in the Data Sources panel are not displayed in the Variables panel.

![hc 063 3](https://user-images.githubusercontent.com/29569434/28970621-1dec8c7c-7921-11e7-90ee-1dc6eeed02e2.PNG)

5. In the Data Sources panel, select a variable. The variable selection on the right hand side (Variables panel) does not change.

![hc 063 4](https://user-images.githubusercontent.com/29569434/28970626-25b48ef0-7921-11e7-9eec-0b0b4ddc45c1.PNG)

### Specifications 

Cate 0.9.0-dev.4
 Windows 7 Professional

**Comment by mzuehlke** [comment]
These two views show independent variables.
The Data Source panel on the left shows all variables that are in a data source.
The Variables panel on the right lists variables that are part of a workspace resource. Only these can be displayed.
To synchronize the selection between these two views is not meaningful.
