### ISSUE TITLE
enso_nino34 operation: "Save File" window instead of "Open File"

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#320]
### Expected behavior

enso_nino34 operation : when selecting a reference file, expect to see an "Open File" window

### Actual behavior

A "Save File" window is displayed instead. 

### Steps to reproduce the problem

1. Open Operations panel. 
2. Select enso_nino34  from the list of operations, click "Apply"
3. Select an input resource and variable (Note: Monthly SST dataset can be generated by running use case #6 happy path)
4. Click on button to select a file.

![hc 062 1](https://user-images.githubusercontent.com/29569434/29030142-01348de2-7b82-11e7-8263-5c6bc3b51068.PNG)

5. In Save window, select an existing .nc file  and click "Save". Click "Yes" to replace. 

![hc 062 3](https://user-images.githubusercontent.com/29569434/29030310-7ae43822-7b82-11e7-8ae4-14f003ef2788.PNG)

 6. The file has been successfully selected.

![hc 062 4](https://user-images.githubusercontent.com/29569434/29030231-472caf82-7b82-11e7-8989-79312a56ebe0.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by HelenClifton** [comment]
Confirmed fixed in cate.0.9.0.dev.6

**Comment by forman** [comment]
I think the parameter name `file` is an issue here on it's own. I also first thought the operation would *write* to that (output) `file`. I suggest the name `lta_input_file` or so would make obvious that this is an input, not an output.
