### ISSUE TITLE
View panel: image layer display options have no effect with 2D Map

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#323]
### Expected behaviour

On View panel. When 2D Map is selected, the options to "Show layer text overlay" and "Split selected image layer" should either work, or be disabled if not applicable.

### Actual behavior

The options to "Show layer text overlay" and "Split selected image layer" do not have any effect with 2D map.

### Steps to reproduce the problem

1. Open GUI and open a dataset. Example: cloud dataset.
2. Open Layers panel and select "Add a new layer"

![hc 069 0a](https://user-images.githubusercontent.com/29569434/29179201-b88e5d4a-7deb-11e7-8fc8-1758e70f1ff3.PNG)

3. Select another variable (Example: cfc)

![hc 069 0b](https://user-images.githubusercontent.com/29569434/29179211-bd949fe8-7deb-11e7-8944-d9173fc2dbb8.PNG)

4. Open View panel. Ensure 3D Globe is selected. Select "Show layer text overlay" and "Split selected image layer". Look at World view.

![hc 069 1](https://user-images.githubusercontent.com/29569434/29179221-c47235aa-7deb-11e7-8f8d-4b3707e750a4.PNG)

5. Switch to 2D map and look at World view.

![hc 069 2](https://user-images.githubusercontent.com/29569434/29179231-c9ba99e4-7deb-11e7-8e69-96cf956c376b.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by JanisGailis** [comment]
Moved to cate-desktop

**Comment by forman** [comment]
Should not have been moved away

**Comment by forman** [comment]
As of IRM6, we'll drop supporting the 2D map

**Comment by forman** [comment]
Closing this because we removed 2D map for 1.0, see #390
