### ISSUE TITLE
colour bar and scroll time-axis

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#328]
### Expected behaviour

One should be able to change and limit the colour bar. In addition, being able to 'scroll' through the time-axis and see the data evolve in time (on the displayed globe) would be nice.

### Actual behaviour

Either the functionality is not yet implemented or I do not find it (i.e. that part might not be intuitive though).

### Specifications 

Cate 0.9.0.dev4

### Comment

I hope this is not cross-posting - as I did not found a comparable issue.

**Comment by thomas-eldridge** [comment]
I think both of these can be accessed by clicking on the 'layers' tab on the top right hand side, although I have found that my datasets regularly do not open for the time period specified - I will be investigating this further and logging a separate issue with my findings.

**Comment by JanisGailis** [comment]
@HerzogStephan @thomas-eldridge Note that issues regarding the graphical user interface should be opened in the 'cate-desktop' repository:
https://github.com/CCI-Tools/cate-desktop/issues

I'll move this one there.

**Comment by mzuehlke** [comment]
Hi @JanisGailis to make tracking them easier we encouraged them to file all bugs in one repository.

**Comment by JanisGailis** [comment]
Ah, thanks! I somehow either missed or forgot that!

**Comment by forman** [comment]
Therefore we reopen it

**Comment by forman** [comment]
...and closing it as the functionality exists, see comment of @thomas-eldridge
