### ISSUE TITLE
1D operation doesn't produce data

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate-core#331]
### Expected behavior

Operations such as t_series_point and t_series_mean (anything which produces 1D output) should automatically open a new view showing data table and plot thereof.

### Actual behavior

Operation resulted in creation of a new resource, upon inspection this was empty, and attempting to open it in a new view showed nothing.

### Specifications

Cate 0.9.0-dev4

**Comment by JanisGailis** [comment]
@thomas-eldridge Can you improve the issue to make it reproducible?

Running the following through cate command line interface works fine:

```shell
# Download some CCI Cloud data
cate ds copy esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1 --name CLOUD_2007 --time '2007-01-01,2007-03-31'

cate ws init
cate res open cloud local.CLOUD_2007
cate res set cloud_cfc select_var ds=@cloud var='cfc'
cate res set cloud_point tseries_point ds=@cloud_sub point=50,50
cate res print cloud_point
cate ws del
```

**Comment by thomas-eldridge** [comment]
Hi Janis, 

From the above it looks as if you've attempted the work using the CLI - I have been using the GUI. I don't know if that will make much difference - I'll try to run the task again and see if I get different results

**Comment by JanisGailis** [comment]
If the issue persists, a new Issue should be opened and described such that it can be reproduced.
