### ISSUE TITLE
New / Edit Operation Step window: Time range fields are being reset

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#335]
### Expected behavior

Using GUI to run through Use Case 6 happy path. Applied a subset_temporal operation. 
In the “New Operation Step” window, selected a start time of 2007-01-01
Then cleared the end time field. Expected the start time which had just been entered not to change.

### Actual behavior

The start time reset itself to 1980-01-01.

Notes: 

- Similar behaviour is seen if the end time has been entered and then the start time is cleared. The end time will reset itself to the current date.
- Similar behaviour is seen in “Edit Operation Step” window as well as “New Operation Step” window
- Similar behaviour is seen for other operations which contain a time range: anomaly_internal and open_dataset

### Steps to reproduce the problem

1. Ensure there is at least one resource of type Dataset in the workspace
2. From operations panel, select subset_temporal then Apply
3. In New Operation Step window, select a Dataset resource
4. Next to TimeRange, enter a start time (the end time field is then automatically populated with today’s date)

![capture1](https://user-images.githubusercontent.com/29569434/29826082-400ee924-8cce-11e7-8cad-a11f311e1d5e.PNG)

5. Clear the end time field and see that the start time has been reset to 1980-01-01

![capture2](https://user-images.githubusercontent.com/29569434/29826105-4fe8081c-8cce-11e7-8f22-152c0b118dd1.PNG)

6. Enter new end time

![capture3](https://user-images.githubusercontent.com/29569434/29826142-68231c96-8cce-11e7-8361-db5a71525af1.PNG)

7. Clear start time. Now end time has been reset.

![capture4](https://user-images.githubusercontent.com/29569434/29826182-840bc872-8cce-11e7-8b0d-f162374ca771.PNG)

### Specifications 

Cate 0.9.0-dev.5
Windows 7 Professional

**Comment by forman** [comment]
We should switch to simple text fields.

**Comment by HelenClifton** [comment]
Confirmed fixed in cate-0.9.0.dev.6
