### ISSUE TITLE
Upsampling failed

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate-core#348]
### Expected behavior

A slave dataset with spatial resolution lower than the master dataset should be resampled to the spatial resolution of the master

### Actual behavior

Error message 'ValueError: O3_du data array of slave dataset is not valid for coregistration. Expected coordinates are (lat, lon, time), received coordinates are ('time', 'layers', 'lat', 'lon'), consider running select_var and/or normalize operations first.'

I tried to select a variable and normalize the ds - still get same error message. Cannot figure out how to select an individual layer within a 3D dataset.

### Steps to reproduce the problem

1. Open ozone dataset as resource
2. Open cloud dataset as resource
3. Apply operation 'coregister' with ozone as slave and cloud as master; use defaults.

Note: downsampling (using ozone as master and cloud as slave) works fine. Further, if the newly resampled cloud ds is used as a slave, and the old cloud ds is used as the master, the operation raises no errors (but does not show data) - implication is that this fails with datasets with a z-dim.

### Specifications 

Cate 0.9.0-dev6

**Comment by JanisGailis** [comment]
#36
