### ISSUE TITLE
Spatial subsetting returned error

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate-core#349]
### Expected behavior

Upon application of spatial subsetting operation, expect lat/lon limits of ds to change.

### Actual behavior

Attempted this with a range  of lons and lats – box went blue, and ‘validate’ button said all clear, then   got error message: "cannot convert value <-20, 20, -20, 20> to PolygonLike".   Tried again with no -ve   lats/lons, and with different dataset: same error message.

### Steps to reproduce the problem

1. Import dataset
2. Select spatial_subset operation from list
3. Type in comma separated longitude and latitude coordinates
4. Run operation

### Specifications 

Cate 0.9.0-dev6

**Comment by mzuehlke** [comment]
The format for the 4 number syntax is: `<lon1>,<lat1>,<lon2>,<lat2>`

So if you use `-20,-20,20,20` it should work. But you are right the validation could do a better job to prevent the input error by the user in the first place.

**Comment by thomas-eldridge** [comment]
perhaps four separate boxes, each with an external label, would be useful for the interface? when I started typing in the box the instructions disappear, and this seems to have played a part in one of Helen's issues (caused, I believe, by typing a '-' instead of a ',' to separate the limits of a temporal subsampling operation).

**Comment by forman** [comment]
@thomas-eldridge we wanted it to be a text field because you can also paste in polygons as WKT (OGC standard). But we may add an extra editor for the 4 coordinates in the future. Please post a feature request for it.

**Comment by forman** [comment]
Can we close this now in favor of #349?
