### ISSUE TITLE
Download datasource fails with JSON error

### ISSUE THREAD

**Issue by mzuehlke** [CCI-Tools/cate-core#355]
### Expected behavior

User should be able to download a remote data source to the local disc.

### Actual behavior

Any download action fails with the following error message:

    make_ds_local() call returned a value that could not be converted to JSON

### Steps to reproduce the problem

1. Select a remote data source
2. Open the download dialog
3. Download it

### Specifications 

cate 0.9.0.dev7

**Comment by kbernat** [comment]
@mzuehlke could you provide more details, I've just checked with CLI and there no problems occurs.

**Comment by mzuehlke** [comment]
It happens always from the GUI. The JSON conversion of the data sources fails.
Please test it using the GUI.

**Comment by kbernat** [comment]
Fix tested on windows/in GUI.
