### ISSUE TITLE
Cate-core build fails on windows with several errors

### ISSUE THREAD

**Issue by kbernat** [CCI-Tools/cate-core#359]
### Expected behavior

Cate-core builds without errors

### Actual behavior

CondaVerificationError: The package for pytest located at D:\Miniconda3\pkgs\pytest-3.2.2-py_0
appears to be corrupted. The path 'resources/cli-64.exe'
specified in the package manifest cannot be found.

... (NEXT ERROR ) ...

ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'conda-forge::pyshp-1.2.12-py_0'.
CondaError: pyc file failed to compile successfully
  python_exe_full_path: D:\Miniconda3\envs\cate-core\python.exe
  py_full_path: D:\Miniconda3\envs\cate-core\Lib\site-packages\shapefile.py
  pyc_full_path: D:\Miniconda3\envs\cate-core\Lib\site-packages\__pycache__\shapefile.cpython-36.pyc

Attempting to roll back.

... (NEXT ERROR ) ...

ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'conda-forge::h5netcdf-0.4.1-py_0'.
CondaError: pyc file failed to compile successfully
  python_exe_full_path: D:\Miniconda3\envs\cate-core\python.exe
  py_full_path: D:\Miniconda3\envs\cate-core\Lib\site-packages\h5netcdf\__init__.py
  pyc_full_path: D:\Miniconda3\envs\cate-core\Lib\site-packages\h5netcdf\__pycache__\__init__.cpython-36.pyc

Attempting to roll back.

### Steps to reproduce the problem

conda env create -n cate-core --file environment.yml

### Specifications 

cate 0.9.0.dev6 on Windows 10 x64

**Comment by kbernat** [comment]
All thee libraries has been updated last week.
A quick workaround is to freeze pyshp, h4netcdf, pytest versions and use previous release.

  # hotfixes
  - pyshp = 1.2.11
  - h5netcdf = 0.4.0 
  - pytest = 3.2.1

**Comment by forman** [comment]
Success with
- pytest >=3.1,<3.2
- pytest-cov >=2.5.1,<2.6
