### ISSUE TITLE
"Window" sub-menu is empty

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#362]
### Expected behavior

Select Window from GUI top menu, expect to see a sub-menu

### Actual behavior

There is a non-selectable item which contains text "Empty"

### Steps to reproduce the problem

1. Select Window from GUI top menu

### Specifications 

cate 0.9.0-dev.6
Windows 7 Professional

**Comment by forman** [comment]
Ok, but it should not be empty on Mac: minimize, close, zoom, to front.
I'll remove it on other OS.

**Comment by HelenClifton** [comment]
Tested with cate-0.9.0-dev7 and confirmed fixed on Windows.
