### ISSUE TITLE
Missing operation deprecation information

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#381]
### Expected behavior

Operations and their inputs shall be tagged as "deprecated" so we can introduce new operation versions with revised signature, or change input names while maintaining backward compatibility.

Deprecated operations and deprecated operation inputs should not appear in the CLI or GUI.

### Actual behavior

As backward compatibility is a requirement, we cannot easily change operation names, their signatures,  and inputs.

### Specifications 

Cate 0.9.0.dev7

**Comment by JanisGailis** [comment]
@forman Can you also put a chapter in operation development guide about this, with a small example how it should be used?

**Comment by forman** [comment]
Done!
