### ISSUE TITLE
Drop 2D map view

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#390]
For Cate Desktop, it is becoming too much work to implement and maintain a harmonized abstraction API on top of 2D map (OpenLayers API) and 3D globe (Cesium API) so that GUI actions perform in a similar way.

As suggested and agreed upon at IRM6 we'd like to drop the 2D map view from Cate Desktop so that users will no longer be able to switch from default 3D globe to 2D map in the **VIEWS** panel. 

The 2D map offered the possibility to set the projection which is in particular useful for polar data products. However, this can still be achieved by the `plot_map()` operation.

For the future, note that also Cesium supports WMS and WMTS imagery sources as OpenLayers does. For Cate, the most beneficial OpenLayers features are the build-in GIS tools that also allow for editing points, lines, polygons. We'll have to search for a Cesium equivalent.

### Specifications 

Cate 0.9.0.dev7

**Comment by JanisGailis** [comment]
I would vote for relegating the map view to a viewer only. I believe that the ability to view the data in different projections is an important feature, and as far as I tried playing around with plot_map operation during the IRM6, many projections didn't work as expected. We have to be careful to not introduce more work by dropping the mapview completely.

**Comment by forman** [comment]
Many OpenLayers projections I've tried so far, especially pole projections, are very buggy (at least in Cate Desktop) and can cause the App to become unresponsive. Even keeping display is sync is a lot of work as you can see from the source code and we haven't even really touched yet vector data layers.

I will leave the code in as it was already a lot of work. But since I have the ok from Ed and Rainer, I like to remove the feature from the 1.0 release. Who knows, maybe someone meanwhile develops an integrated Cesium/OpenLayers component, ideally for ReactJS.

**Comment by JanisGailis** [comment]
Of course. I just provided my input, but you know best the amount of hassle required to even keep the map view up to date, so ultimately it's your decision!

And 'it took a lot of work' is not a great reason for leaving code in :)

**Comment by forman** [comment]
I fully agree that the projections are an advantage, but remember, Cate is not a GIS and the 2D map view is just a *view*. Regarding projections, I guess it is much more important to users if they can
* create maps using some defined CRS which they can store and paste into their publications or export to a Shapefile. 
* reproject/resample their source grid to some target grid with a defined CRS

**Comment by esacci** [comment]
Interesting discussion and thank you for invitation to comment. 

Is there a way this discussion can extend to the Champion Users also, or perhaps that's already the case anyway?

All the best,

Ed

**Comment by forman** [comment]
@esacci Hi Ed, yes, it is already the case
@JanisGailis see also: Create scaleable multi-layer map #79

**Comment by forman** [comment]
Just commented out GUI code that renders the switch between 2D/3D. `OpenLayers`and `proj4` are no longer required but still in dependencies. They add some overhead to the packaging and may be removed from `package.json` soon.

**Comment by forman** [comment]
The fix is in https://github.com/CCI-Tools/cate-desktop/tree/390-nf-drop_2d_map_view

**Comment by barsten** [comment]
I think the 2D map view is the one that scientists are used to use. I woudl give it preference over the 3D globe.

**Comment by HerzogStephan** [comment]
@barsten This is a valid argument.

But having the non-scientists in mind I would stick to 3D. The 2D is still available within the "plot_map"-operation (in a way).

**Comment by forman** [comment]
@barsten You can still go from 3D to planar 2D (geographic lat/lon "projection ") and 2.5D perspective by clicking the upper right corner of the World View, the globe icon button. We may be able to add mercator projection for the 2D view later. 

The feature that shall be dropped here is a 2D *map* view (using OpenLayers) that uses a given projection / CRS which b.t.w. as often buggy and caused the display to hang. 

In addition, from a technical point of view, the 3D Cesium globe offers us a lot more visualisation options for the future (e.g. point cloud visualisation, terrain, stacks of atmospheric layers).

**Comment by forman** [comment]
* https://blog.klokantech.com/2014/11/ol3-cesium-third-dimension-for.html
* https://cesium.com/blog/2014/11/18/openlayers3-adds-cesium/

**Comment by forman** [comment]
About to remove dependency to OpenLayers and proj4 and to remove modules that use it: MapView, OpenLayersMap, ProjectionDialog, ProjectionField, projection-util. 

Here is the tag that still contains all the code: https://github.com/CCI-Tools/cate-desktop/releases/tag/1.1.0.dev1-with-ol
