### ISSUE TITLE
Type validation that can understand Python "types" created with the typing package

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#46]
isinstance hiccups on validating types from the typing package when using the cli interface. See #45

**Comment by JanisGailis** [comment]
One way how to solve this would be to not type such objects in the method signature, but use something like this:
```python
@op_input('date', type='Date')
@op_input('geometry', type='Polygon')
def some_method(date, geometry, something: str = 'default'):
    pass
```

**Comment by JanisGailis** [comment]
I think I have a workable solution for this.

**Comment by forman** [comment]
@JanisGailis, please have a look what @mzuehlke and I wrote. We now have a better understanding, so lets discuss on Monday and combine forces! Our implementation is a little more type-safe and when defining operations, and we don't need the alias. I also like that the type classes are called "<Type>Like" and have an "accepts" method to check if any value is like <Type>. 
Cheers
    Norman

**Comment by JanisGailis** [comment]
We now have complex types.
