### ISSUE TITLE
Pearson correlation time by time

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#57]
It should be possible to carry out Pearson correlation on time by time basis for time/lat/lon datasets.

**Comment by JanisGailis** [comment]
This is now possible using the timeseries operation beforehand. A dedicated interface for time by time correlation for the Pearson correlation operation is due v2.0.

**Comment by forman** [comment]
Is this issue a requirement or just an idea?

**Comment by JanisGailis** [comment]
It was part of the operation specification for Pearson correlation. However, the functionality is there, just not in a single step. Maybe that's even better. I'm not sure if taking spatial mean should be part of a correlation operation.
