### ISSUE TITLE
Allow arbitrary polygons for spatial subsetting

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#72]
For spatial subsetting, users should be able to define a region of interest by providing arbitrary polygons.

Users may provide such region polygons by
- Constructing a geometry-like object (API)
- Reading from a file (API, CLI, GUI)
  - Geometry-WKT
  - Shapefile
  - GeoJSON
- Providing a WKT string (API, CLI)
- Drawing a polygon on a map or globe (GUI only)

**Comment by lkeupp** [comment]
actually, this is not neccessary for UC6. 
But non-rectangular polygons will be needed in the future and the can be used for Chris's idea regarding testing of other regions for index calculation

**Comment by JanisGailis** [comment]
See also #46
