### ISSUE TITLE
Calculation of anomalies

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#73]
The toolbox shall offer one or more operations that allows for computing anomalies w.r.t. to a given reference e.g. a climatology. 

The set of required operations should also include the calculation of the _absolute anomaly on the log-transformed_ dataset variables.

TDB: Always provide reference or e.g. compute climatologies implicitly?

**Comment by lkeupp** [comment]
when thinking again about the Meeting, I was wondering "climatology" was supposed to mean climatology (= long stable time series e.g. 1970-1999) or climatological mean (long-term mean of daily, monthly, yearly resolution, e.g. 1970-1999 Janualy mean of SST)

**Comment by JanisGailis** [comment]
There are assumptions on doing anomaly calculation (the variables have to be named the same in the 'reference' and ' data' datasets). Otherwise this is implemented.
