### ISSUE TITLE
ENSO index calculation from SST data

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#74]
Provide the means to perform an [El Niño-Southern Oscillation](https://de.wikipedia.org/wiki/El_Ni%C3%B1o-Southern_Oscillation) (ENSO) index calculation from SST. This may either be provided as a standard built-in operation or as a demonstration for a user-supplied plug-in.

A more sophisticated version of this operation is the [Multivariate ENSO Index](https://en.wikipedia.org/wiki/Multivariate_ENSO_index) (MEI), see issue #75.

**Comment by JanisGailis** [comment]
It was mentioned during the IPM2 it was mentioned that ENSO 3.4 should be used.

**Comment by lkeupp** [comment]
the index is called Niño3.4 or N3.4 index and is one of the Standard ENSO indices it is defined as the 
normalized5-month running mean of the anomaly of N3.4 mean SST 
N3.4 Region is a rectangular region in the equatorial Pacific (120–170°W, 5°S–5°N)
sometimes different rules for regional delineation or smoothing/standardization are used

**Comment by JanisGailis** [comment]
Does this mean we have to have the 'long term average' tool or climatology to be able to get the anomaly of mean SST over N3.4 in order to calculate the indices?

**Comment by lkeupp** [comment]
yes, the index calculation was the reason for starting the climatology discussion

**Comment by JanisGailis** [comment]
@lkeupp Are there 'climatology' datasets available somewhere that I could use to try and do UC06 without developing the long-term averages tool first? As in, if I understand correctly, I'm interested in long-term monthly average reference data for SST.

Correct me if I'm wrong and I need something else in addition to SST reference data. Or if I need something else completely!

**Comment by lkeupp** [comment]
I wrote an email to Kevin to ask regarding an adequate SST reference data set.

When searching myself, I found These datasets from the NOAA ESRL:

Sea Surface Temperature Long Term Means 
[1961-1990](ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2/sst.ltm.1961-1990.nc) or 
[1971-2000 ](ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2/sst.ltm.1961-1990.nc) from  http://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oisst.v2.html 

Soil Moisture 	Monthly Long Term Means [1981-2010](ftp://ftp.cdc.noaa.gov/Datasets/cpcsoil/soilw.mon.ltm.v2.nc) from http://www.esrl.noaa.gov/psd/data/gridded/data.cpcsoil.html





http://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oisst.v2.html
