### ISSUE TITLE
Provide additional doc chapters

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#77]
Some chapters should still be added to documentation at [ect-core.readthedocs.io](http://ect-core.readthedocs.io/en/latest/)
- [x] Concepts
- [x] Developer Guide
- [x] How to Contribute
- [x] Terms

The _Concepts_ chapter should include
- what workflows are and how they are used and explain workflow JSON format
- what workspaces are and how they are used

The _Developer Guide_ chapter should include
- how to use the API
- how to develop plugins, see #170 

The _How to Contribute_ chapter should include:
- how to submit an issue
- how to do pull requests

**Comment by JanisGailis** [comment]
We now have the 'Developer Guide' chapter.
