### ISSUE TITLE
spatial subsetting by point location

### ISSUE THREAD

**Issue by lkeupp** [CCI-Tools/cate-core#83]
It should be possible to define an area of interest by one latitude and one longitude coordinate

**Comment by lkeupp** [comment]
but time series extraction for point data works

**Comment by JanisGailis** [comment]
I think this is possible. I'll check.

**Comment by JanisGailis** [comment]
Possible with ops.tseries_poing(poing='lon, lat')

**Comment by forman** [comment]
Poing?

**Comment by mzuehlke** [comment]
@JanisGailis  meant: `ops.tseries_point(point='lon, lat')`.

**Comment by forman** [comment]
I believe `tseries_point()` must get also an `index: dict = None` argument so that we can `var.sel(**index)` to create time series from variables that have more than the usual (time, lat, lon) dimensions.
