### ISSUE TITLE
save results of spatial correlation analysis as ASCII table or netcdf 

### ISSUE THREAD

**Issue by lkeupp** [CCI-Tools/cate-core#87]
to better analyse spatially resolved correlation results

**Comment by JanisGailis** [comment]
I have to double check this, but I believe we already have this. Netcdf for sure is there, a text file as well, but it's just a dump of NetCDF, not a pretty printed ASCII table.

I'll verify what we have here.

**Comment by forman** [comment]
Can we close this?

**Comment by JanisGailis** [comment]
Yes.

I have actually opted to remove the 'file' parameter from correlation operation. The operation produces an xarray dataset, which then can be saved using dedicated io operations that we have. This way 'concerns are separated', all saving is done in one place and the operation invocation dialog becomes simpler.
