### ISSUE TITLE
Plotting should be able to recognize Julian calendar time

### ISSUE THREAD

**Issue by lkeupp** [CCI-Tools/cate-core#89]
for temporal subsetting, Julian calendar time is meanwhile recoginzed #60
but in plots, the time is still not human readable
![cc_africa_ts_1](https://cloud.githubusercontent.com/assets/19472165/19599191/d135df68-979f-11e6-8276-80a2c2cde43c.png)

**Comment by JanisGailis** [comment]
In my opinion, this should be solve upon reading in a dataset and transforming the time axis to a known and expected format. What is your take on this @forman ?

**Comment by JanisGailis** [comment]
#23

**Comment by JanisGailis** [comment]
All datasets we work with are now expected to have datetime time coordinates. This is either taken care by xarray when opening a dataset, or if xarray doesn't handle a particular time definition, by ```ops.harmonization```, which handles Julian Date times for us now.
