### ISSUE TITLE
annotation language

### ISSUE THREAD

**Issue by lkeupp** [CCI-Tools/cate-core#90]
at the moment, time annotations (jan 2007 etc.) are plotted in the system language (in the read the docs documentation, the annotations are Norwegian, while they are German in the figures I produced).

(This issue is of negligible importance at the moment and will be solved autmatically by the introduction of customizable plots)

**Comment by JanisGailis** [comment]
Should they always be English instead?

**Comment by lkeupp** [comment]
for scientific analysis I'd say: yes
but as we want to address non-scientific users, too, there should be an easy way to modify the language settings for annotations

**Comment by JanisGailis** [comment]
OK, so we could have an option that lets one choose between English or System, where English is default.

**Comment by forman** [comment]
I agree unless this produces a lot of work. Internationalization (of plots or any other software component) is currently not a requirement at all. ESA's default language is English UK.

**Comment by JanisGailis** [comment]
So then let's just make sure that the Toolbox produces output in English.

**Comment by forman** [comment]
Is this still an issue?

**Comment by JanisGailis** [comment]
In the latest plotting implementation 'time' ticks are formatted as '2007-01-01' making this bug deprecated.
