### ISSUE TITLE
no dependent and variable daata in correlation analysis

### ISSUE THREAD

**Issue by lkeupp** [CCI-Tools/cate-core#91]
In contrast to regression analysis, where it has to be clearley stated which dataset is the dependent and which the Independent one, in correlation Analysis it doesn't matter. Therefore, the decription in the documentation for the correlation operation is not right. I know, I could change it myself but I didn't want to meddle in your operation scripts.

**Comment by JanisGailis** [comment]
Can you look at this description?

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.pearsonr.html

It's the function we're using behind the scenes. They do mention that 'as x increases, so does y' and 'as x increases, y decreases'. So, in a sense, x seems to be the independent one, whereas y the dependent one.

I can of course change the description, I just want to make sure that we're doing the right thing.

So, should I change the description to remove 'dependent' and 'independent'?

**Comment by lkeupp** [comment]
the scipy description is right in my opinion. It doesn't mention dependent/independent but uses "as x increases, so does y" just for pointing out what it's about. 
What I wanted to say is that in correlations you can interchange x and y but for regression (linear: y = ax + b) this is not possible. Thus, it would be good to change the description to remove dependent/Independent.
